version: 2
jobs:
  build:
    # machine: true
    machine:
      image: ubuntu-2004:202010-01
    
    steps:
      - checkout
      - run:
          name: Install Job dependencies
          command: |
            sudo apt update
            sudo apt install -y jq
            sudo apt install -y moreutils
            sudo snap install yq
            # sudo snap install snapcraft --classic
            # sudo snap install lxd
            # sudo /snap/bin/lxd.migrate -yes
            # sudo /snap/bin/lxd waitready
            # sudo /snap/bin/lxd init --auto
      - run: 
          name: Version check
          command: |
            LATEST_VERSION_TAG="$(curl https://api.github.com/repos/RPCS3/rpcs3-binaries-linux/releases/latest -s | jq .tag_name -r)"
            CURRENT_VERSION_SNAP="$(snap info rpcs3-emu | grep edge | head -n 2 | tail -n 1 | awk -F ' ' '{print $2}')"
            LATEST_VERSION_COMMIT=${LATEST_VERSION_TAG#build-}
            LATEST_VERSION="$(curl https://api.github.com/repos/RPCS3/rpcs3-binaries-linux/releases/latest -s | jq .name -r)"

            # compare versions
            if [ $CURRENT_VERSION_SNAP != $LATEST_VERSION ]; then
                echo "versions don't match, github: $LATEST_VERSION snap: $CURRENT_VERSION_SNAP"
                echo "updating rpcs3 source commit"
                yq w -i snap/snapcraft.yaml parts.rpcs3.source-commit $LATEST_VERSION_COMMIT
                export BUILD="true"
                export LATEST_VERSION
                export LATEST_VERSION_COMMIT
                export CURRENT_VERSION_SNAP
            else
                echo "versions match, github: $LATEST_VERSION snap: $CURRENT_VERSION_SNAP"
                export BUILD="false"
            fi
      - run:
          name: Versions match - Cancel
          command: |
            if [ ${BUILD} == false ]; then
              circleci-agent step halt
            fi
      - run:
          name: Snap build
          command: |
            sudo snapcraft --use-lxd --enable-experimental-package-repositories
      - run:
          name: Snap Test
          command: |
            sudo snap install *.snap --dangerous
            snap run rpcs3-emu.rpcs3 --version
      - run:
          name: "Publish to Snap Store"
          command: |
            mkdir .snapcraft
            echo $SNAP_STORE_LOGIN | base64 --decode --ignore-garbage > .snapcraft/store-login.txt
            snapcraft login --with-file .snapcraft/store-login.txt
            snapcraft upload *.snap --release edge
            rmdir .snapcraft
      - run:
          name: Updating versions.json
          command:  |
            cat versions.json | jq '.edge = "${LATEST_VERSION}"' | sponge versions.json
            git config --global user.name 'Nightmayr'
            git config --global user.email 'umayr23@gmail.com'
            git commit -am "Updating version [ci skip]"
            git push -q https://${GITHUB_PAT}@github.com/Nightmayr-snaps/rpcs3-snap.git master

